---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: organizations.grafana.k8spin.cloud
spec:
  scope: Namespaced
  group: grafana.k8spin.cloud
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            spec:
              type: object
              properties:
                datasources:
                  description: Grafana datasources
                  type: array
                  items:
                    type: object
                    required: [name, data]
                    properties:
                      name:
                        type: string
                      data:
                        type: string
                dashboards:
                  description: Grafana dashboards
                  type: array
                  items:
                    type: object
                    required: [name, data]
                    properties:
                      name:
                        type: string
                      data:
                        type: string
      additionalPrinterColumns:
      - jsonPath: .spec.datasources[*].name
        name: Datasources
        type: string
      - jsonPath: .spec.dashboards[*].name
        name: Dashboards
        type: string
  names:
    kind: Organization
    plural: organizations
    singular: organization
    shortNames:
      - orgs
      - org
