apiVersion: grafana.k8spin.cloud/v1
kind: Datasource
metadata:
  name: example-prom-datasource
spec:
  organizations:
  - example.com
  - k8spin
  datasource:
    name: "Example Prometheus Datasource"
    data: |-
      {
        "type": "prometheus",
        "access": "proxy",
        "url": "http://prometheus.monitoring:9090"
      }
